apiVersion: apps/v1
kind: Deployment
metadata:
  name: development-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dev-app
  template:
    metadata:
      labels:
        app: dev-app
    spec:
      containers:
      - name: dev-container
        image: gcr.io/qwiklabs-gcp-03-5397b8a5aaa0/sample-app:v2.0
        ports:
        - containerPort: 8080
